version: '3.9'

services:
  db:
    image: postgres:latest
    volumes: 
      - data:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    hostname: db
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "${PG_PORT}:${PG_PORT}"
  dba:
    image: dpage/pgadmin4
    volumes: 
      - pgadmin:/var/lib/pgadmin
      #so docker is creating a volumes for you and also managing it.
    hostname: dba
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_ADMIN_NAME}
      - PGADMIN_DEFAULT_PASSWORD=${PG_ADMIN_PASS}
    ports:
      - "${PG_ADMIN_PORT}:${PG_ADMIN_PORT}"
  # consumer
  consumer: 
    build: ./consumer/
    hostname: consumer
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - CONSUMER_PORT=${CONSUMER_PORT}
    command: python consumer.py 
    volumes:
      - ./consumer/code:/app
    ports:
      - "${CONSUMER_PORT}:${CONSUMER_PORT}"
  api:
    build: ./api/
    hostname: ${API_HOST}
    environment:
      - API_PORT=${API_PORT}
    command: python api.py
    volumes:
      - ./api/code:/app
    ports:
      - "${API_PORT}:${API_PORT}"

volumes:
  data:
  pgadmin: