FROM dpage/pgadmin4
ENV PGADMIN_DEFAULT_EMAIL=admin@admin.com
ENV PGADMIN_DEFAULT_PASSWORD=pass
#Why using ENV? System use Envirnment vairiables to find credentials.
#But it generate long command lines if you don't do it in docker file.
EXPOSE 80
